# Generated by release-cli.yml. Edits here are overwritten by the next release.
class Ryra < Formula
  desc "Rich client for herdr, the terminal workspace manager for AI coding agents"
  homepage "https://ryra.dev"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_arm do
      url "https://pkg.ryra.dev/bin/ryra-aarch64-apple-darwin.tar.gz"
      sha256 "8c4183e30cf2beeb4f0bc732d4f095f3e795092519186bcd45806c21eee18c6a"
    end
    on_intel do
      url "https://pkg.ryra.dev/bin/ryra-x86_64-apple-darwin.tar.gz"
      sha256 "390cd3e112f266954562a760b5cf156ebf84dfbd71ea35c10f94785ff8fc6710"
    end
  end

  on_linux do
    on_arm do
      url "https://pkg.ryra.dev/bin/ryra-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "dc70461290acb145285c7cf7692e8bf4bf604dd01bf5776406bb9157477ffedf"
    end
    on_intel do
      url "https://pkg.ryra.dev/bin/ryra-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "3022603f908fe55b415b79ba5bc675afd84963d651ddd175de85a52a0a6e5ccd"
    end
  end

  def install
    bin.install "ryra"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ryra --version")
  end
end
