# Generated by release-cli.yml. Edits here are overwritten by the next release.
class Ryra < Formula
  desc "Rich client for herdr, the terminal workspace manager for AI coding agents"
  homepage "https://ryra.dev"
  version "0.1.13"
  license "MIT"

  on_macos do
    on_arm do
      url "https://pkg.ryra.dev/bin/ryra-aarch64-apple-darwin.tar.gz"
      sha256 "990352c9660ec2889e09761702b719d2c4569e0ca9afbb378fb8c0f83a8bc4c1"
    end
    on_intel do
      url "https://pkg.ryra.dev/bin/ryra-x86_64-apple-darwin.tar.gz"
      sha256 "eb2e5e2eae9fa36f778eb48e4d82f940f72eb1c5f8c39e2a2e462c89750e045f"
    end
  end

  on_linux do
    on_arm do
      url "https://pkg.ryra.dev/bin/ryra-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "d401b1dd1db4ea02fe7f029edd99466c2e417ff3de77b5f4630130ee8eb50609"
    end
    on_intel do
      url "https://pkg.ryra.dev/bin/ryra-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "048dd2ff8469551e791a1f6e93c6ba2395b03cae4b50a86b87e9ae234868b49f"
    end
  end

  def install
    bin.install "ryra"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ryra --version")
  end
end
